In [1]:
#imported librarries
import tensorflow as tf 
import numpy as np

In [3]:
#create dummy dataset
x=tf.random.uniform((100,1))
y=(x+5)*0.3

In [4]:
type(x),type(y)

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

In [6]:
x.shape, y.shape

(TensorShape([100, 1]), TensorShape([100, 1]))

In [8]:
#define a simple nueral network
model=tf.keras.Sequential(
    [
        tf.keras.layers.Input(name='InputLayer',shape=[1]),
        tf.keras.layers.Dense(100,name='H1'),
        tf.keras.layers.Dense(1,name='H2')
    ]
)

In [9]:
#summarize the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 H1 (Dense)                  (None, 100)               200       
                                                                 
 H2 (Dense)                  (None, 1)                 101       
                                                                 
Total params: 301 (1.18 KB)
Trainable params: 301 (1.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.layers[0].weights[0].shape

TensorShape([1, 100])

In [12]:
#Train neural network
model.compile(loss='MSE',optimizer='adam')

In [18]:
model.fit(x, y, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 6ms/step - loss: 2.3732e-14
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 2.3732e-14
Epoch 3/100
4/4 [==============================] - 0s 10ms/step - loss: 2.3874e-14
Epoch 4/100
4/4 [==============================] - 0s 6ms/step - loss: 2.3874e-14
Epoch 5/100
4/4 [==============================] - 0s 7ms/step - loss: 2.3732e-14
Epoch 6/100
4/4 [==============================] - 0s 6ms/step - loss: 2.3732e-14
Epoch 7/100
4/4 [==============================] - 0s 6ms/step - loss: 2.3732e-14
Epoch 8/100
4/4 [==============================] - 0s 9ms/step - loss: 2.3874e-14
Epoch 9/100
4/4 [==============================] - 0s 7ms/step - loss: 2.3874e-14
Epoch 10/100
4/4 [==============================] - 0s 8ms/step - loss: 2.3874e-14
Epoch 11/100
4/4 [==============================] - 0s 7ms/step - loss: 2.3874e-14
Epoch 12/100
4/4 [==============================] - 0s 8ms/step - loss: 2.3874e-14
Epoch 13/100

In [21]:
(20.0 * model.layers[0].weights[0]) + (3.0 * model.layers[0].weights[1]) + ( model.layers[1].weights[1])

<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
array([[-2.8967779 ,  3.2495391 , -1.3842471 ,  2.723488  ,  0.6925937 ,
        -2.688561  , -3.4627302 ,  2.8964524 , -1.350523  , -1.5135994 ,
         1.7679737 ,  3.6371944 , -2.2172837 , -1.9403939 ,  3.4959404 ,
        -1.7594388 , -1.2526349 , -1.0685431 ,  2.8657088 ,  4.0364556 ,
        -3.1400163 ,  3.6177971 , -0.50048184,  1.4922067 , -3.905917  ,
        -1.5444386 ,  1.6320407 ,  3.1623538 , -2.6294413 ,  2.489205  ,
         0.7230803 ,  1.506261  , -1.5207679 ,  1.0518749 , -4.7825823 ,
        -4.2719173 ,  0.04710868,  2.920048  , -3.555042  , -4.939091  ,
         1.1597228 ,  3.0863318 , -3.669329  , -3.5913815 ,  0.84986246,
        -3.7133005 , -2.2633998 ,  2.1789324 , -3.1077597 ,  4.0267315 ,
         2.2523303 ,  4.871753  ,  0.76116395,  1.8315566 , -0.95896304,
        -2.8570385 ,  0.06214237, -3.5844784 , -0.01573768,  1.4007947 ,
         3.9403722 ,  3.178663  ,  2.9164069 , -2.7101753 , -2.4162712 ,
 

In [23]:
! pip install  pydot

In [24]:
! pip install graphviz

In [26]:
tf.keras.utils.plot_model(model)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


## predict

In [27]:
model.predict([[9]])

1/1 [==============================] - 1s 587ms/step


array([[4.200002]], dtype=float32)

In [28]:
(np.array([9]) + 5) * 0.3

array([4.2])